### ISSUE TITLE
crash when a mocha test fails with an error that has a circular data structure

### ISSUE THREAD

**Issue by jandockx** [Wizcorp/mocha-reporter#5]
````
     >>> logs: Error: TypeError: Converting circular structure to JSON
     >>> logs:     at JSON.stringify (<anonymous>)
     >>> logs:     at makeSimple (node_modules/format-error/index.js:36:28)
     >>> logs:     at format (node_modules/format-error/index.js:39:21)
     >>> logs:     at Runner.<anonymous> (node_modules/mocha-reporter/index.js:283:18)
````

in `runner.on('fail'…`, the `test.err` is formatted with `'format-error'`

`'format-error'` has a known problem with circular data structures since 2014 (
[#2](https://github.com/EndangeredMassa/format-error/issues/2)) which will not be fixed.

The author:

> I think that this module shouldn't really exist. I'd rather fix this in prettyjson itself,

**Comment by jandockx** [comment]
maybe `util.inspect` would be a sensible replacement?

**Comment by jandppw** [comment]
https://www.npmjs.com/package/@ppwcode/mocha-ssst
https://bitbucket.org/ppwcode/mocha-ssst
